// global
export const UPDATE_LOADING = 'UPDATE_LOADING'
export const UPDATE_DIRECTION = 'UPDATE_DIRECTION'
export const UPDATE_PAGETITLE = 'UPDATE_PAGETITLE'
export const UPDATE_TABBAR = 'UPDATE_TABBAR'

// 字典
export const UPDATE_DIC = 'UPDATE_DIC'

// article
export const ARTICLE_LIST = 'ARTICLE_LIST'
export const ADD_ARTICLE_LIST = 'ADD_ARTICLE_LIST'
export const REQUEST_ARTICLE_LIST = 'REQUEST_ARTICLE_LIST'
export const GET_ARTICLE_LIST_FAILURE = 'GET_ARTICLE_LIST_FAILURE'

// user
export const UPDATE_USERINFO = 'UPDATE_USERINFO'
